###
#  This file was generated by bootstrap do not edit manually
###

variable "project_id" {
  type = string
}

variable "region" {
  type = string
}

variable "owner" {
  type = string
}

variable "environment" {
  type    = string
  default = "development"
}
