###
#  This file was generated by bootstrap do not edit manually
###

remote_state {
  backend = "gcs"
  config = {
    bucket   = "${terraform_bucket}"
    prefix   = "$${path_relative_to_include()}/terraform.tfstate"
    project  = "${project_id}"
    location = "${region}"
  }

}

terraform {
  before_hook "providers" {
    commands = ["init"]
    execute  = ["cp", "$${get_parent_terragrunt_dir()}/../templates/providers.tf", "."]
  }

  before_hook "versions" {
    commands = ["init"]
    execute  = ["cp", "$${get_parent_terragrunt_dir()}/../templates/versions.tf", "."]
  }

}