###
#  This file was generated by terragrunt do not edit manually
###

terraform {
  required_version = "~> 0.12.8"

  required_providers {
    google      = "~> 3.33.0"
    google-beta = "~> 3.33.0"
    random      = "~> 2.2"
  }
}